"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

from .cors import CORS_ALLOWED_ORIGINS  # noqa: F401

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
# Las credenciales viven en backend/.env, que NO se sube al repositorio (SRS 1.4-j).
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="django-insecure--y^+dei-k^bf62ru8^(5#y$gk#7zxfw*)um%r=wdk3x8y(+c0=",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Aquí van la apps para volver Django en backend puro y el CORS
    "rest_framework",
    "corsheaders",
    # Aquí van las apps propias de nuestro projecto
    "chats",
    "knowledge",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # CORS
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "es-co"

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


# ---------------------------------------------------------------------------
# Proveedor de IA y parámetros del pipeline RAG
# ---------------------------------------------------------------------------
# AI_PROVIDER: "gemini" (Google AI Studio, capa gratuita) u "openai".
# La clave se lee de backend/.env y nunca se escribe en el código (SRS 1.4-j).

AI_PROVIDER = env("AI_PROVIDER", default="gemini")
AI_API_KEY = env("AI_API_KEY", default="")

# Los nombres de modelo cambian con el tiempo y los viejos se retiran.
# Si una llamada falla con 403 o 404, revisa qué modelos acepta tu clave:
#   https://generativelanguage.googleapis.com/v1beta/models?key=TU_CLAVE
_DEFAULT_MODELS = {
    "gemini": {"chat": "gemini-3.6-flash", "embedding": "gemini-embedding-001"},
    "openai": {"chat": "gpt-4o-mini", "embedding": "text-embedding-3-small"},
}
_models = _DEFAULT_MODELS.get(AI_PROVIDER, _DEFAULT_MODELS["gemini"])

AI_CHAT_MODEL = env("AI_CHAT_MODEL", default=_models["chat"])
AI_EMBEDDING_MODEL = env("AI_EMBEDDING_MODEL", default=_models["embedding"])

# Tope de tokens de la respuesta. En los modelos Gemini 3.x el
# razonamiento interno se descuenta de aquí, así que conviene holgado.
AI_MAX_OUTPUT_TOKENS = env.int("AI_MAX_OUTPUT_TOKENS", default=2048)

# Cuánto razona el modelo antes de responder: minimal, low, medium o high.
# Solo aplica a los modelos Gemini 3.x. Vacío = no se envía el parámetro.
AI_THINKING_LEVEL = env("AI_THINKING_LEVEL", default="low")

# Cuántos fragmentos se piden por llamada al calcular embeddings.
# Lotes grandes son más rápidos pero chocan antes con el límite por
# minuto del tier gratuito. Bájalo si aparecen errores 429.
AI_EMBED_BATCH_SIZE = env.int("AI_EMBED_BATCH_SIZE", default=10)

# Cuántos fragmentos se le pasan al modelo como contexto.
RAG_TOP_K = env.int("RAG_TOP_K", default=4)

# Similitud coseno mínima para considerar que un fragmento responde la
# pregunta. Por debajo de este valor el sistema declara su limitación en
# lugar de responder (US10).
RAG_MIN_RELEVANCE = env.float("RAG_MIN_RELEVANCE", default=0.55)
