# Generated by Django 6.1.1 on 2026-09-13 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ej: Reglamento Académico de los programas de pregrado",
                        max_length=200,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1",
                        help_text="Versión del documento. Ej: 2024-1",
                        max_length=50,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Enlace al documento oficial publicado por la Universidad.",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha desde la cual rige esta versión.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Solo los documentos activos se usan para responder. Las versiones retiradas se conservan para trazabilidad.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Orden del fragmento dentro del documento."
                    ),
                ),
                (
                    "article_ref",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Artículo 42. Vacío si el fragmento no corresponde a un artículo.",
                        max_length=120,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Vector de embedding. Lista de floats.",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "fragmento",
                "verbose_name_plural": "fragmentos",
                "ordering": ["document", "position"],
            },
        ),
    ]
