# Generated by Django 6.1.1 on 2026-09-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='Nueva conversación NA', max_length=100),
        ),
    ]
