# Generated by Django 6.1.1 on 2026-09-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chat_last_seen_alter_chat_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_seen',
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='Nueva conversación NA', max_length=100),
        ),
    ]
