# Generated by Django 6.1.1 on 2026-09-13 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_remove_chat_last_seen_alter_chat_title"),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(default="Nueva conversación", max_length=100),
        ),
        migrations.CreateModel(
            name="MessageSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_title", models.CharField(max_length=200)),
                ("article_ref", models.CharField(blank=True, max_length=120)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Texto literal del artículo citado, para mostrarlo al usuario."
                    ),
                ),
                ("relevance", models.FloatField(default=0.0)),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citations",
                        to="knowledge.chunk",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="chats.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-relevance"],
            },
        ),
    ]
