# Generated by Django 6.0.7 on 2026-08-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_genre_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descripcion',
            new_name='description',
        ),
    ]
